In [1]:
import theano
from theano import tensor as T, function

import numpy as np

# Function definitions

In [17]:
X = T.matrix('x')
Y = X ** 2
Z = T.grad(Y.sum(), X)
F = function([X], [Y, Z])

In [25]:
x = np.ones((2, 2)) * 3
y, z = F(x)

# Print results

In [26]:
print(x)
print('-'*12)
print(y)
print('-'*12)
print(z)

[[ 3.  3.]
 [ 3.  3.]]
------------
[[ 0.67462554  0.67462554]
 [ 0.67462554  0.67462554]]
------------
[[-0.1023451 -0.1023451]
 [-0.1023451 -0.1023451]]


# Symbolic vs Shared variables in Theano

In [28]:
X

x

In [30]:
X_shared = theano.shared( np.ones((3,3)) )

In [34]:
X_shared.get_value()

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])