In [1]:
import numpy as np

In [2]:
from keras.datasets import mnist

Using TensorFlow backend.


In [15]:
from keras.utils import np_utils

In [3]:
(x_train,y_train),(x_test,y_test) = mnist.load_data()

In [4]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [5]:
x_train.shape

(60000, 28, 28)

In [6]:
y_train.shape

(60000,)

In [10]:
x_test.shape

(10000, 28, 28)

In [11]:
y_test.shape

(10000,)

In [12]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [3]:
from keras.models import Sequential

In [4]:
from keras.layers import Dense

In [5]:

y_train=np.array([
    0,0,0,0,
    0,0,0,1,
    0,0,1,1,
    0,1,1,1
])
x_test=np.array([
    [2,1],
    [2,2],
    [3,0],
    [3,1]
])
y_test=np.array([
    0,
    1,
    0,
    1
])

In [6]:
x_train=np.array([
    [0,0],
    [0,1],
    [0,2],
    [0,3],
    [1,0],
    [1,1],
    [1,2],
    [1,3],
    [2,0],
    [2,1],
    [2,2],
    [2,3],
    [3,0],
    [3,1],
    [3,2],
    [3,3]
])

In [23]:
x_train = x_train.astype("float32")

In [25]:
x_train

array([[[[0., 0.]]],


       [[[0., 1.]]],


       [[[0., 2.]]],


       [[[0., 3.]]],


       [[[1., 0.]]],


       [[[1., 1.]]],


       [[[1., 2.]]],


       [[[1., 3.]]],


       [[[2., 0.]]],


       [[[2., 1.]]],


       [[[2., 2.]]],


       [[[2., 3.]]],


       [[[3., 0.]]],


       [[[3., 1.]]],


       [[[3., 2.]]],


       [[[3., 3.]]]], dtype=float32)

In [24]:
y_train = y_train.astype("float32")

In [8]:
y_train.shape

(16,)

In [9]:
x_test.shape

(4, 2)

In [10]:
y_test.shape

(4,)

In [11]:
x_train = x_train.reshape(x_train.shape[0], 1, 1,2)

In [12]:
x_train.shape

(16, 1, 1, 2)

In [13]:
x_test = x_test.reshape(x_test.shape[0],1,1,2)

In [14]:
x_test.shape

(4, 1, 1, 2)

In [16]:
y_train = np_utils.to_categorical( y_train, 2)

In [17]:
y_train.shape

(16, 2)

In [18]:
y_train

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [20]:
y_test = np_utils.to_categorical( y_test, 2)

In [21]:
y_test

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.]], dtype=float32)

In [49]:
model = Sequential()

In [52]:
model.add( Dense(1, input_shape=(2,)))

In [53]:
model.compile( loss='categorical_crossentropy', optimizer='adadelta')

In [54]:
model.layers

In [55]:
model.inputs

[<tf.Tensor 'dense_6_input:0' shape=(?, 2) dtype=float32>]

In [47]:
model.get_config()

{'name': 'sequential_3',
 'layers': [{'class_name': 'Dense',
   'config': {'name': 'dense_4',
    'trainable': True,
    'batch_input_shape': (None, 1, 2),
    'dtype': 'float32',
    'units': 1,
    'activation': 'linear',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'VarianceScaling',
     'config': {'scale': 1.0,
      'mode': 'fan_avg',
      'distribution': 'uniform',
      'seed': None}},
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'activity_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None}}]}

In [48]:
model.fit( x_train, y_train, 
          batch_size=4, 
          epochs=2,
          verbose=1,
          validation_data=(x_test,y_test)
         )

ValueError: Error when checking input: expected dense_4_input to have 3 dimensions, but got array with shape (16, 1, 1, 2)